version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: docker
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: docker
    volumes:
      - ./db/data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    restart: always
    environment:
      DB_URL: jdbc:postgresql://db:5432/docker # We need to set the service name instead of localhost!!
      DB_USER: docker
      DB_PW: secret
    ports:
      - "8080:8080"
    depends_on:
      - db
