version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: docker
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: docker
    volumes:
      - ./db/data:/var/lib/postgresql/data
